datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com

  kubelet:
    tlsVerify: false

  apm:
    portEnabled: true
    socketEnabled: true

  processAgent:
    enabled: true
    processCollection: true

  logs:
    enabled: true
    containerCollectAll: true

  dogstatsd:
    useSocketVolume: true

  env:
    - name: DD_DBM_PROPAGATION_MODE
      value: "full"

clusterAgent:
  enabled: true
  replicas: 1

agents:
  containers:
    agent:
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "400m"
    traceAgent:
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
